import type { TrackerInfo } from '../types';

/**
 * Analytics trackers database
 */
export const ANALYTICS_TRACKERS: Record<string, TrackerInfo> = {
  'google-analytics.com': {
    domain: 'google-analytics.com',
    name: 'Google Analytics',
    category: 'Analytics',
    description: 'Website analytics and user behavior tracking',
    riskLevel: 'low',
  },
  'googletagmanager.com': {
    domain: 'googletagmanager.com',
    name: 'Google Tag Manager',
    category: 'Analytics',
    description: 'Tag management system for tracking codes',
    riskLevel: 'low',
  },
  'clarity.ms': {
    domain: 'clarity.ms',
    name: 'Microsoft Clarity',
    category: 'Analytics',
    description: 'User session recording and heatmaps',
    riskLevel: 'high',
  },
  'hotjar.com': {
    domain: 'hotjar.com',
    name: 'Hotjar',
    category: 'Analytics',
    description: 'User behavior analytics and session recordings',
    riskLevel: 'high',
  },
  'mixpanel.com': {
    domain: 'mixpanel.com',
    name: 'Mixpanel',
    category: 'Analytics',
    description: 'Product analytics and user tracking',
    riskLevel: 'medium',
  },
  'segment.com': {
    domain: 'segment.com',
    name: 'Segment',
    category: 'Analytics',
    description: 'Customer data platform and tracking',
    riskLevel: 'medium',
  },
  'omtrdc.net': {
    domain: 'omtrdc.net',
    name: 'Adobe Analytics',
    category: 'Analytics',
    description: 'Adobe marketing cloud analytics',
    riskLevel: 'medium',
  },
  'salesforce.com': {
    domain: 'salesforce.com',
    name: 'Salesforce Tracking',
    category: 'Analytics',
    description: 'CRM and marketing automation tracking',
    riskLevel: 'medium',
  },
  'hubspot.com': {
    domain: 'hubspot.com',
    name: 'HubSpot',
    category: 'Analytics',
    description: 'Marketing automation and CRM tracking',
    riskLevel: 'medium',
  },
  'intercom.io': {
    domain: 'intercom.io',
    name: 'Intercom',
    category: 'Analytics',
    description: 'Customer messaging and behavior tracking',
    riskLevel: 'medium',
  },
  'amplitude.com': {
    domain: 'amplitude.com',
    name: 'Amplitude',
    category: 'Analytics',
    description: 'Product analytics and user behavior tracking',
    riskLevel: 'medium',
  },
  'fullstory.com': {
    domain: 'fullstory.com',
    name: 'FullStory',
    category: 'Analytics',
    description: 'User session recording and analytics',
    riskLevel: 'high',
  },
  'logrocket.com': {
    domain: 'logrocket.com',
    name: 'LogRocket',
    category: 'Analytics',
    description: 'Session replay and performance monitoring',
    riskLevel: 'high',
  },
  'heap.io': {
    domain: 'heap.io',
    name: 'Heap Analytics',
    category: 'Analytics',
    description: 'Automatic event tracking and user analytics',
    riskLevel: 'medium',
  },
  'kissmetrics.com': {
    domain: 'kissmetrics.com',
    name: 'KISSmetrics',
    category: 'Analytics',
    description: 'Customer analytics and behavior tracking',
    riskLevel: 'medium',
  },
  'crazyegg.com': {
    domain: 'crazyegg.com',
    name: 'Crazy Egg',
    category: 'Analytics',
    description: 'Heatmap and user behavior analytics',
    riskLevel: 'medium',
  },
  'mouseflow.com': {
    domain: 'mouseflow.com',
    name: 'Mouseflow',
    category: 'Analytics',
    description: 'Session replay and heatmap analytics',
    riskLevel: 'high',
  },
  'smartlook.com': {
    domain: 'smartlook.com',
    name: 'Smartlook',
    category: 'Analytics',
    description: 'Session recording and analytics platform',
    riskLevel: 'high',
  },
  'inspectlet.com': {
    domain: 'inspectlet.com',
    name: 'Inspectlet',
    category: 'Analytics',
    description: 'Session recording and user behavior tracking',
    riskLevel: 'high',
  },
  'quantcast.com': {
    domain: 'quantcast.com',
    name: 'Quantcast',
    category: 'Analytics',
    description: 'Audience measurement and analytics',
    riskLevel: 'medium',
  },
  'comscore.com': {
    domain: 'comscore.com',
    name: 'ComScore',
    category: 'Analytics',
    description: 'Digital analytics and audience measurement',
    riskLevel: 'medium',
  },
  'nielsen.com': {
    domain: 'nielsen.com',
    name: 'Nielsen',
    category: 'Analytics',
    description: 'Audience measurement and market research',
    riskLevel: 'medium',
  },
};
